### ISSUE TITLE
Review Studiewijzer

### ISSUE THREAD

**Issue by stgm** [minprog/programmeren-1#15]
https://prog120.mprog.nl/syllabus (na inloggen)

@Jelleas @WouterVrielink Kunnen jullie allebei een keer een review doen en hier discussiepunten achterlaten?

Mijn bedoeling is dat deze dan als template kan dienen voor de andere cursussen (met name natuurlijk de CS50-gebaseerde cursussen).

**Comment by stgm** [comment]
Ik dacht nog een weekschemaatje te tekenen ofzo. De minimumeisen gaan heel erg over wat je in de week moet doen en is misschien toch wel overzichtelijker om een deel daarvan grafisch over te brengen.

**Comment by stgm** [comment]
Oh, nog wat: er wordt al een beetje naar verwezen maar nog niet zo duidelijk. Een idee is om elke week een paar redelijk open-ended technische vragen als huiswerk op te geven voor het mentoraat. Waarschijnlijk gekopppeld aan de basisboek-onderwerpen (kopje 'oefeningen').

**Comment by WouterVrielink** [comment]
Ik vind die persoonlijke TODO-list links geweldig! 

Bij de minimumeisen voor "verbetert" een "en" te veel.
Waarom heb je het hier opgedeeld in tweeën? 
Wat houd de checkup in?


De overige delen worden onderaan uitgelegd, maar deze informatie wordt bovenaan al "gebruikt". Is het nog steeds het idee dat er een introcollege komt? Want dan is dit niet zo'n probleem.

Eindcijfer staat ver van de beoordeling van de opdrachten af. Daarnaast noem je het gemengd opdrachten en modules.

Dit gaat meer over de stijl van de pagina, maar ik vind het niet bijzonder duidelijk dat de dingen met een pijltje ervoor drop downs zijn.

Ik mis inderdaad iets van een weekschema. Is het ondertussen niet zo dat we de weken gelijk aan het lopen hebben aan de modules? Of is het nog steeds van woensdag tot woensdag? 

Heb je een voorbeeld van zo'n open-ended technische vraag?

**Comment by stgm** [comment]
- Ik heb e.e.a. verbeterd
- De todo-lists werken alleen nog niet, weet niet of ik dat op tijd voor elkaar krijg ;-)
- Checkup is informele kickoff van de dag met de mentorgroep (zonder mentor), ideeën?
- Weekschema was meer "hoe ziet een week eruit", maar dat heb ik al een klein beetje toegevoegd bovenaan
- Ik weet niet of we nog technische vragen doen, want:

Na overleg met @Jelleas een nieuw proces ingevoegd waarmee studenten moeten gaan werken. Ze krijgen een weekpartner met wie ze de oplossingen ontwerpen maar niet implementeren. Bij mentoraat dan steeds starten/oefenen met het ontwerpen (als dat te plannen is). Ook code review gedeeltelijk bij mentoraat? Dit vraagt om meer overleg :-)
