### ISSUE TITLE
Scratch - Ideas

### ISSUE THREAD

**Issue by FloorLeur** [minprog/programmeren-1#24]
De links van _Gingerbread Tales_ en _Cookie Love Story_ verwijzen naar dezelfde pagina (dus de link van _Gingerbread Tales_ klopt niet).

**Comment by stgm** [comment]
Kun je de juiste link achterhalen?

**Comment by stgm** [comment]
De nieuwste open versie van CS50 staat hier trouwens: https://cs50.harvard.edu/x/2021/
Daar staan ook hun versies van de opdrachten.

**Comment by FloorLeur** [comment]
Juiste link voor Gingerbread Tales: [https://scratch.mit.edu/projects/277536784/](https://scratch.mit.edu/projects/277536784/)
