### ISSUE TITLE
Boek: Variabelen - How to submit

### ISSUE THREAD

**Issue by FloorLeur** [minprog/programmeren-1#26]
Ik zou hier duidelijker zeggen dat als je meer dan x aantal fouten hebt, je de test niet gehaald hebt en opnieuw moet doen – dus dat je screenshot moet laten zien dat je maximaal x fouten in de toets hebt gemaakt. Daar was afgelopen semester onduidelijkheid over (en daardoor gedoe voor de assistenten, die aan veel studenten moesten vragen om hun toets nog een keer te maken als ze veel fouten hadden).

**Comment by stgm** [comment]
We vragen vanaf nu gewoon 100% goed, en dat heb ik er inderdaad expliciet bijgezet.
