### ISSUE TITLE
Mario

### ISSUE THREAD

**Issue by FloorLeur** [minprog/programmeren-1#28]
Als je op Mario klikt, krijgt de tab de titel _Less - Programmeren 1_. Kan dat _Mario - Programmeren 1_ worden?

**Comment by FloorLeur** [comment]
Zelfde voor Find: Die heet ook _Less - Programmeren 1_ ipv _Find - Programmeren 1_.

**Comment by FloorLeur** [comment]
Voor Fifteen: Die heet nu _More - Programmeren 1_ ipv _Fifteen - Programmeren 1_.

**Comment by stgm** [comment]
Bug aangemaakt voor de website!
