### ISSUE TITLE
Oefenen: Big-O

### ISSUE THREAD

**Issue by FloorLeur** [minprog/programmeren-1#66]
De stukjes code die hierin staan voldoen niet aan onze eigen stijl-eisen: ik mis veel spaties om operatoren heen en curly brackets bij for-loops en if-statements.

**Comment by stgm** [comment]
Toegevoegd: "Note that the code style might not exactly be as prescribed in the style guide and might even be a bit misleading. Read the code very carefully to determine the correct answer."
De spaties om operators hou ik nog even vast.
