### ISSUE TITLE
Fifteen - Specification

### ISSUE THREAD

**Issue by FloorLeur** [minprog/programmeren-1#71]
> Implement init in such a way that the board is initialized to a pseudorandom but solvable configuration.

Waarom pseudorandom? Bovenaan staat dat je het bord altijd op dezelfde manier initialiseert, met de tiles in reverse order.

**Comment by stgm** [comment]
Klopt inderdaad, maar dit gaf dan weer het idee om een versie van de opdracht te maken waar dit wél moet ;-)
